version: 2.1
jobs:
  # test:
  #   docker:
  #     - image: circleci/node:16
  #   steps:
  #     - checkout
  #     - run:
  #         name: Run Build
  #         command: |
  #           npm ci
  #           npm run build
  #     - persist_to_workspace:
  #         root: .
  #         paths:
  #           - dist/*
  #           - package.json
  #           - package-lock.json
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Run Build
          command: |
            npm ci
            npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist/moots-tooltip
            - package.json
            - package-lock.json

  publish-beta:
    docker:
      - image: circleci/node:16
    steps:
      - attach_workspace:
          at: ./dist/moots-tooltip/
      - run:
          name: Authenticate with NPM
          command: |
            printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" > .npmrc
            npm whoami
      - run:
          name: Deploy to NPM
          command: |
            ls
            pwd
            npm publish --access public --tag beta
  publish:
    docker:
      - image: circleci/node:16
    steps:
      - attach_workspace:
          at: ./dist/moots-tooltip/
      - run:
          name: Authenticate with NPM
          command: |
            printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" > .npmrc
            npm whoami
      - run:
          name: Deploy to NPM
          command: |
            ls
            pwd
            npm publish --access public
workflows:
  version: 2
  ci:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      # - test:
      #     filters:
      #       tags:
      #         only: /.*/

      - publish-beta:
          requires:
            - build
          # requires:
          #   - test
          filters:
            tags:
              only: /v([0-9])*.([0-9])*.([0-9])*-.*/
            branches:
              ignore: /.*/

      - publish:
          requires:
            - build
          # requires:
          #   - test
          filters:
            tags:
              only: /v([0-9])*.([0-9])*.([0-9])*/
            branches:
              ignore: /.*/
